"""HCMVoiceAgent: runs one patient conversation and applies the safety guardrails.

Each patient turn goes through take_turn():
0. The opening: Clara asks for the patient by name and says nothing health-related until they
   confirm. If someone else answers, she asks when to reach the patient and notes it.
1. An instant keyword check for emergencies (a safety net that never waits on the model).
2. One model request that returns Clara's reply plus a clinical emergency assessment, the
   patient's sentiment and the conversation state (see prompts.py, RESPONSE FORMAT).
3. Guardrails on the reply: diagnoses, medical advice, medication changes and promises are
   replaced with honest, safe wording.
4. The closing sequence: when the patient is done (or says goodbye), Clara offers a feedback
   form, notes their answer, thanks them and ends the call.
"""

import json
import logging
import re
from dataclasses import dataclass
from typing import Optional, Tuple

from .. import config
from .guardrails import GuardrailViolation, VoiceAgentGuardrails
from .llm import LLM, create_llm
from .prompts import get_system_prompt

logger = logging.getLogger(__name__)

REFUSAL_REPLY = ("I'm not able to help with that on this call, but your care team can. "
                 "Is there anything else on your mind today?")
ERROR_REPLY = "I'm having trouble connecting right now. Please try again in a moment."
REPLACED_VIOLATIONS = (GuardrailViolation.MEDICAL_ADVICE, GuardrailViolation.MEDICAL_DIAGNOSIS,
                       GuardrailViolation.PRESCRIPTION_CHANGE, GuardrailViolation.PROMISE)

# Clara can't schedule, transfer or arrange callbacks, so these only promise a note for the care team.
SAFE_FALLBACKS = {
    GuardrailViolation.MEDICAL_DIAGNOSIS:
        "I'm not able to say what that means, but it's important to tell your doctor. "
        "I'll note it for your care team.",
    GuardrailViolation.MEDICAL_ADVICE:
        "I can't give medical advice, but your doctor or pharmacist can help with that question. "
        "I'll note it for your care team.",
    GuardrailViolation.PRESCRIPTION_CHANGE:
        "Please don't change any medication without talking to your doctor or pharmacist first. "
        "I'll note your question for your care team.",
    GuardrailViolation.PROMISE:
        "That's not something I can do on this call, but I'll note it for your care team "
        "so they can follow up.",
}

# Fixed emergency messages: never generated by the model.
EMERGENCY_REPLIES = {
    "medical": (
        "I'm really sorry you're going through this, and I want you to get help right away. "
        "If this is a medical emergency, please hang up and call 9 1 1 now. "
        "I'm also flagging this call for your care team. Goodbye."
    ),
    "mental_health": (
        "I'm really sorry you're feeling this way, and I'm glad you told me. "
        "Please call or text 9 8 8, the Suicide and Crisis Lifeline, right now, "
        "or call 9 1 1 if you're in immediate danger. "
        "I'm also flagging this call for your care team. Goodbye."
    ),
}

FEEDBACK_QUESTION = "Before you go, would you like a short feedback form by text message?"
NEUTRAL_SENTIMENT = 0.5
SENTIMENT_WEIGHT = 0.6  # how much each new reading moves the score; the rest is the running value
CONVERSATION_STATES = ("ongoing", "needs_met", "patient_done")

GOODBYE = re.compile(r"\b(bye|goodbye|hang up|that's all|that is all|gotta go|have to go)\b", re.IGNORECASE)
# Opening: Clara confirms she's speaking with the patient before mentioning anything health-related.
WRONG_NUMBER = re.compile(r"\b(wrong number|no one (by|with|named) that name|nobody (by|with|named) that name|"
                          r"don't know (a|an|any|anyone|anybody)|no .{0,20} lives here)\b", re.IGNORECASE)
NOT_AVAILABLE = re.compile(r"^\W*(no|nope|nah)\b|\b(not here|isn't here|is not here|not available|isn't available|"
                           r"not home|isn't home|out right now|can't come to the phone|asleep|at work|busy right now|"
                           r"call back later|not in)\b", re.IGNORECASE)
CONFIRMED = re.compile(r"\b(yes|yeah|yep|yup|speaking|that's me|that is me|it's me|this is (she|he|her|him|me)|"
                       r"you got (her|him|me)|uh huh|mhm|that's right|correct|i am|sure)\b", re.IGNORECASE)
THIS_IS = re.compile(r"\b(?:this is|it's|i'm|i am|my name is)\s+([A-Za-z][A-Za-z'-]+)", re.IGNORECASE)
NOT_NAMES = {"she", "he", "her", "him", "me", "his", "the", "a", "not", "just", "fine", "good", "busy", "sorry"}
TIME_WORDS = re.compile(r"\b(tomorrow|tonight|today|morning|afternoon|evening|noon|weekend|monday|tuesday|"
                        r"wednesday|thursday|friday|saturday|sunday|next week|later|o'clock|\d{1,2}(:\d{2})?\s*"
                        r"(am|pm|a\.m\.|p\.m\.)?|after \w+|before \w+|around \w+)\b", re.IGNORECASE)
MAX_VERIFY_ATTEMPTS = 2

# "Is there anything else I can help you with?" answered with "No, that's all, thanks."
ANYTHING_ELSE = re.compile(r"\banything else\b", re.IGNORECASE)
NOTHING_ELSE = re.compile(r"^\W*(no|nope|nah|not really|nothing|that's (all|it|everything)|that is all|"
                          r"i'm (good|fine|all set)|i think that's it|all good|we're good)\b", re.IGNORECASE)
MORE_TO_SAY = re.compile(r"\b(but|actually|one more|also|another|wait|question|what about|how about)\b",
                         re.IGNORECASE)
# Closing turns skip the model, so clear thanks or relief there nudges the sentiment up instead.
POSITIVE = re.compile(r"\b(thank you|thanks so much|thanks a lot|helpful|appreciate|that helps|great|perfect|"
                      r"wonderful|glad)\b", re.IGNORECASE)
POSITIVE_READING = 0.8
YES = re.compile(r"\b(yes|yeah|yep|yup|sure|ok|okay|please|absolutely|definitely|why not|sounds good)\b",
                 re.IGNORECASE)
NO = re.compile(r"\b(no(?! problem| worries)|nope|nah|not really|don't want|do not want|don't need|"
                r"i'm good|im good|i'll pass|pass on)\b", re.IGNORECASE)


@dataclass
class Emergency:
    kind: str     # "medical" or "mental_health"
    reason: str
    source: str   # "keyword" (instant check) or "ai" (the model's clinical assessment)


@dataclass
class Turn:
    """What Clara does after one patient turn."""
    reply: str                              # what Clara says
    action: str                             # "listen" (keep talking) or "hang_up" (after saying the reply)
    sentiment: float                        # running sentiment, 0 (negative) to 1 (positive)
    emergency: Optional[Emergency] = None
    blocked: Optional[dict] = None          # a reply the guardrails replaced: {"rule", "text"}
    end_reason: Optional[str] = None        # set when action is "hang_up"
    feedback_opt_in: Optional[bool] = None  # set when the patient answers the feedback question
    identity: Optional[str] = None          # when the opening resolves: confirmed, not_available or wrong_number
    spoke_with: Optional[str] = None        # who answered instead, if they gave a name
    callback_time: Optional[str] = None     # when to reach the patient, in the words used
    phase: str = "conversation"             # "verify", "callback", "conversation", "feedback" or "ended"
    used_model: bool = False


class HCMVoiceAgent:
    """One patient conversation: emergency checks, model replies, guardrails and the closing sequence."""

    def __init__(self, api_key: Optional[str] = None, settings: Optional[config.Settings] = None,
                 llm: Optional[LLM] = None):
        settings = settings or config.load()
        self.provider = settings.llm_provider
        self.llm = llm or create_llm(settings, api_key)
        self.guardrails = VoiceAgentGuardrails()
        self.initialize_call()

    def initialize_call(self, patient_context: Optional[dict] = None) -> None:
        self.patient_context = patient_context or {}
        self.conversation_history: list[dict[str, str]] = []
        self.is_emergency = False
        self.escalation_reason: Optional[str] = None
        self.emergency: Optional[Emergency] = None
        self.last_blocked_reply: Optional[dict] = None
        self.sentiment = NEUTRAL_SENTIMENT
        # With a known name, the call opens by confirming who answered; otherwise it starts the check-in.
        self.phase = "verify" if self._patient_name() else "conversation"
        self.verify_attempts = 0
        self.identity: Optional[str] = None
        self.spoke_with: Optional[str] = None
        self.callback_time: Optional[str] = None
        self.closing_reason: Optional[str] = None
        self.end_reason: Optional[str] = None
        self.feedback_opt_in: Optional[bool] = None
        if self.patient_context:
            logger.info("Call initialized for patient: %s", self.patient_context.get("name", "Unknown"))

    def start_call(self) -> str:
        """Begin the conversation: returns Clara's first words and records them in the history."""
        greeting = self.opening()
        self.conversation_history = [{"role": "user", "content": "[The call has connected.]"},
                                     {"role": "assistant", "content": greeting}]
        return greeting

    def opening(self) -> str:
        """Clara's first words. Nothing health-related is said until the patient confirms who they are."""
        name = self._patient_name()
        if self.phase == "verify":
            return (f"Hi, I'm Clara, a virtual assistant from your health insurance care team. "
                    f"May I speak with {name}, please?")
        return ("Hi, this is Clara, a virtual assistant from your health insurance care team. "
                "I'm calling to check in on how you're doing with your diabetes management. "
                "How have you been feeling lately?")

    # ---- The turn ----

    def take_turn(self, patient_message: str) -> Turn:
        """Decide Clara's next words and whether the call continues."""
        self.last_blocked_reply = None
        said = patient_message.strip()

        # 1. Instant safety net, in every phase.
        is_emergency, reason = self.process_patient_input(said)
        if is_emergency:
            kind = "mental_health" if reason.startswith("Mental health") else "medical"
            return self._emergency_turn(said, Emergency(kind, reason.split(":", 1)[-1].strip(), "keyword"))

        nothing_else = self._asked_anything_else() and NOTHING_ELSE.search(said) and not MORE_TO_SAY.search(said)
        # Steps 2-4 don't ask the model, so read clear thanks or relief from the words themselves.
        if (self.phase == "feedback" or GOODBYE.search(said) or nothing_else) and POSITIVE.search(said):
            self._update_sentiment(POSITIVE_READING)

        # Opening: confirm who answered, or take a time to reach the patient.
        if self.phase == "verify":
            return self._verify(said)
        if self.phase == "callback":
            return self._record_callback(said)

        # 2. Answering the feedback question ends the call.
        if self.phase == "feedback":
            return self._feedback_answer(said)

        # 3. Saying goodbye goes straight to the closing sequence.
        if GOODBYE.search(said):
            self._remember(said, FEEDBACK_QUESTION)
            return self._start_closing("Patient said goodbye", FEEDBACK_QUESTION)

        # 4. "No" to "anything else?" closes the call without waiting on the model.
        if nothing_else:
            closing = f"I'm glad I could help. {FEEDBACK_QUESTION}"
            self._remember(said, closing)
            return self._start_closing("Patient's needs addressed", closing)

        # 5. Ask the model.
        self.conversation_history.append({"role": "user", "content": said})
        try:
            raw = self.llm.complete(get_system_prompt(self.patient_context), self.conversation_history,
                                    json_mode=True)
        except Exception as e:
            logger.error("Error generating response: %s", e)
            return self._reply(ERROR_REPLY, used_model=True)
        if raw is None:
            # Azure's safety filter blocks self-harm content outright. On a care call that means a
            # possible crisis, so it gets the crisis message, never a brush-off.
            if "self_harm" in getattr(self.llm, "last_filter_categories", set()):
                self.conversation_history.pop()
                return self._emergency_turn(said, Emergency("mental_health", "content safety flagged possible "
                                                            "self-harm", "ai"))
            return self._reply(REFUSAL_REPLY, used_model=True)

        result = parse_model_output(raw)
        self._update_sentiment(result["sentiment"])
        if result["emergency"]:
            self.conversation_history.pop()  # _emergency_turn records the patient's words itself
            return self._emergency_turn(said, Emergency(result["emergency"]["kind"],
                                                        result["emergency"]["reason"], "ai"))

        reply = self._apply_guardrails(result["reply"] or "Sorry, could you say that again?")
        if result["state"] == "patient_done":
            closing = f"{reply} {FEEDBACK_QUESTION}" if reply else FEEDBACK_QUESTION
            self.conversation_history.append({"role": "assistant", "content": closing})
            return self._start_closing("Patient's needs addressed", closing, used_model=True)
        return self._reply(reply, used_model=True)

    def generate_response(self, patient_message: str) -> str:
        """Clara's reply to one patient message (the text only; see take_turn for the full result)."""
        return self.take_turn(patient_message).reply

    def process_patient_input(self, patient_message: str) -> Tuple[bool, str]:
        """Keyword emergency check. Returns (is_emergency, reason)."""
        is_emergency, reason = self.guardrails.check_patient_statement(patient_message)
        if is_emergency:
            self.is_emergency = True
            self.escalation_reason = reason
            logger.warning("EMERGENCY DETECTED: %s", reason)
        return is_emergency, reason

    # ---- Steps ----

    def _reply(self, text: str, used_model: bool = False) -> Turn:
        if not self.conversation_history or self.conversation_history[-1]["role"] != "assistant":
            self.conversation_history.append({"role": "assistant", "content": text})
        return Turn(reply=text, action="listen", sentiment=self.sentiment, blocked=self.last_blocked_reply,
                    phase=self.phase, used_model=used_model)

    def _apply_guardrails(self, reply: str) -> str:
        violation, detail = self.guardrails.check_agent_response(reply)
        if violation in REPLACED_VIOLATIONS:
            logger.warning("GUARDRAIL VIOLATION: %s - %s", violation.value, detail)
            self.last_blocked_reply = {"rule": violation.value, "text": reply}
            return SAFE_FALLBACKS[violation]
        return reply

    def _emergency_turn(self, said: str, emergency: Emergency) -> Turn:
        self.is_emergency = True
        self.emergency = emergency
        self.escalation_reason = f"{emergency.kind} emergency ({emergency.source}): {emergency.reason}"
        logger.warning("EMERGENCY (%s, %s): %s", emergency.kind, emergency.source, emergency.reason)
        reply = EMERGENCY_REPLIES[emergency.kind]
        self._remember(said, reply)
        self.phase, self.end_reason = "ended", "Emergency detected"
        return Turn(reply=reply, action="hang_up", sentiment=self.sentiment, emergency=emergency,
                    end_reason=self.end_reason, phase=self.phase, used_model=emergency.source == "ai")

    def _start_closing(self, reason: str, reply: str, used_model: bool = False) -> Turn:
        self.phase, self.closing_reason = "feedback", reason
        return Turn(reply=reply, action="listen", sentiment=self.sentiment, blocked=self.last_blocked_reply,
                    phase=self.phase, used_model=used_model)

    def _feedback_answer(self, said: str) -> Turn:
        wants_form = bool(YES.search(said)) and not NO.search(said)
        self.feedback_opt_in = wants_form
        name = self.patient_context.get("name")
        thanks = f"Thank you for your time today{', ' + name if name and name != 'there' else ''}. Take care. Goodbye."
        reply = (f"I've noted that you'd like the feedback form. {thanks}" if wants_form
                 else f"No problem. {thanks}")
        self._remember(said, reply)
        self.phase, self.end_reason = "ended", self.closing_reason or "Patient's needs addressed"
        return Turn(reply=reply, action="hang_up", sentiment=self.sentiment, end_reason=self.end_reason,
                    feedback_opt_in=wants_form, phase=self.phase)

    def _patient_name(self) -> Optional[str]:
        name = (self.patient_context.get("name") or "").strip()
        return name if name and name.lower() != "there" else None

    def _verify(self, said: str) -> Turn:
        """Is this the patient? Confirmed → the check-in; someone else → ask when to reach the patient."""
        name = self._patient_name()
        first = name.split()[0].lower()
        stated = next((m.group(1) for m in THIS_IS.finditer(said) if m.group(1).lower() not in NOT_NAMES), None)
        if stated and stated.lower().endswith(("'s", "’s")):
            stated = None  # "this is Maria's husband" names the patient, not the speaker

        if WRONG_NUMBER.search(said):
            reply = "I'm sorry to have bothered you. Have a good day. Goodbye."
            self._remember(said, reply)
            return self._end_opening("wrong_number", "Wrong number", reply)

        is_someone_else = stated is not None and stated.lower() != first
        if NOT_AVAILABLE.search(said) or is_someone_else:
            self.spoke_with = stated.capitalize() if is_someone_else else None
            if TIME_WORDS.search(said) and not re.fullmatch(r"\W*(no|nope|nah)\W*", said, re.IGNORECASE):
                return self._record_callback(said)  # they already said when, e.g. "she's back after 5"
            # Privacy: say nothing about the reason for the call to anyone but the patient.
            reply = f"No problem. What would be a good time to reach {name}?"
            self._remember(said, reply)
            self.phase = "callback"
            return Turn(reply=reply, action="listen", sentiment=self.sentiment, identity="not_available",
                        spoke_with=self.spoke_with, phase=self.phase)

        if CONFIRMED.search(said) or (stated is not None and stated.lower() == first):
            self.identity = "confirmed"
            reply = (f"Thanks, {name.split()[0]}. I'm calling to check in on how you're doing with your diabetes "
                     "management. How have you been feeling lately?")
            self._remember(said, reply)
            self.phase = "conversation"
            return Turn(reply=reply, action="listen", sentiment=self.sentiment, identity="confirmed", phase=self.phase)

        self.verify_attempts += 1
        if self.verify_attempts >= MAX_VERIFY_ATTEMPTS:
            reply = f"I'm sorry, I'll let you go. What would be a good time to reach {name}?"
            self.phase = "callback"
        else:
            reply = f"Sorry, I didn't catch that. Am I speaking with {name}?"
        self._remember(said, reply)
        return Turn(reply=reply, action="listen", sentiment=self.sentiment, phase=self.phase)

    def _record_callback(self, said: str) -> Turn:
        """Note when to reach the patient. No promise to call: scheduling callbacks comes later."""
        self.callback_time = said.strip()
        reply = "Thank you, I've noted that. Have a good day. Goodbye."
        self._remember(said, reply)
        turn = self._end_opening("not_available", "Patient not available", reply)
        turn.callback_time = self.callback_time
        return turn

    def _end_opening(self, identity: str, reason: str, reply: str) -> Turn:
        self.identity, self.phase, self.end_reason = identity, "ended", reason
        return Turn(reply=reply, action="hang_up", sentiment=self.sentiment, end_reason=reason, identity=identity,
                    spoke_with=self.spoke_with, phase=self.phase)

    def _asked_anything_else(self) -> bool:
        last = next((m["content"] for m in reversed(self.conversation_history) if m["role"] == "assistant"), "")
        return bool(ANYTHING_ELSE.search(last))

    def _remember(self, said: str, reply: str) -> None:
        self.conversation_history += [{"role": "user", "content": said}, {"role": "assistant", "content": reply}]

    def _update_sentiment(self, reading: Optional[float]) -> None:
        if reading is not None:
            self.sentiment = round((1 - SENTIMENT_WEIGHT) * self.sentiment + SENTIMENT_WEIGHT * reading, 2)

    # ---- Wrap-up ----

    def end_call(self) -> dict:
        summary = {
            "patient": self.patient_context.get("name", "Unknown"),
            "call_duration_turns": len(self.conversation_history),
            "emergency_detected": self.is_emergency,
            "escalation_reason": self.escalation_reason,
            "requires_care_manager_followup": self.is_emergency or self.escalation_reason is not None,
            "final_sentiment": self.sentiment,
            "end_reason": self.end_reason,
            "feedback_form_requested": self.feedback_opt_in,
            "identity": self.identity,
            "spoke_with": self.spoke_with,
            "callback_time": self.callback_time,
            "conversation": self.conversation_history,
        }
        logger.info("Call ended. Summary: %s",
                    json.dumps({k: v for k, v in summary.items() if k != "conversation"}, indent=2))
        return summary

    def get_conversation_transcript(self) -> str:
        transcript = ""
        for msg in self.conversation_history:
            role = "Patient" if msg["role"] == "user" else "Agent"
            transcript += f"\n{role}: {msg['content']}\n"
        return transcript


def parse_model_output(raw: str) -> dict:
    """Read the model's JSON turn. Anything malformed falls back to treating the text as the reply."""
    fallback = {"reply": raw.strip(), "emergency": None, "sentiment": None, "state": "ongoing"}
    text = raw.strip()
    if text.startswith("```"):
        text = text.strip("`").removeprefix("json").strip()
    try:
        data = json.loads(text)
    except ValueError:
        start, end = text.find("{"), text.rfind("}")
        try:
            data = json.loads(text[start:end + 1]) if 0 <= start < end else None
        except ValueError:
            data = None
    if not isinstance(data, dict) or not isinstance(data.get("reply"), str):
        return fallback

    emergency = None
    flag = data.get("emergency")
    if isinstance(flag, dict) and flag.get("detected") is True:
        kind = flag.get("type") if flag.get("type") in ("medical", "mental_health") else "medical"
        emergency = {"kind": kind, "reason": str(flag.get("reason") or "described urgent symptoms")[:200]}

    sentiment = data.get("sentiment")
    if isinstance(sentiment, bool) or not isinstance(sentiment, (int, float)):
        sentiment = None
    else:
        sentiment = min(1.0, max(0.0, float(sentiment)))

    state = data.get("conversation_state")
    return {"reply": data["reply"].strip(), "emergency": emergency, "sentiment": sentiment,
            "state": state if state in CONVERSATION_STATES else "ongoing"}
